/**
 @file      voxel3d_vd55h1_info.cpp
 @brief     5VSTDON ToF camera info
 @author    Jackie Lee
 @copyright Copyright (c) 2025 5Voxel Co., Ltd.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string>
#include "voxel3d_vd55h1_info.h"

struct __LUT_CODES {
    unsigned short code;
    std::string name;
};

struct __LUT_REG {
    unsigned short reg_addr;
    std::string reg_name;
};

const __LUT_CODES lut_error_codes[] = {
    {7936, "PMB_ERROR_DATA_READY_HIGH_TIMEOUT"},
    {1308, "VTSENS_ERROR_FLAG125_FLAG135_OVERFLOW"},
    {1045, "CRM_ERROR_PIX_CLK_TARGET"},
    {5, "TOP_ERROR_FOV_X_START_NOT_MULTIPLE_OF_2"},
    {1285, "VTSENS_ERROR_MODE_FLAG125"},
    {517, "XP70PATCH_ERROR_BAD_MD5SUM"},
    {6, "TOP_ERROR_FOV_X_START_NOT_MULTIPLE_OF_4"},
    {1284, "VTSENS_ERROR_FLAG125"},
    {33, "TOP_ERROR_ISLGEN_BOT_TIMEOUT"},
    {1543, "NVM_ERROR_WRITE_TIMEOUT"},
    {1280, "VTSENS_ERROR_TIMEOUT"},
    {4096, "XP70T1REPLICA_ERROR_VERSION"},
    {1311, "VTSENS_ERROR_MODE_CLUSTER_FLAG125_FLAG135_OVERFLOW"},
    {7938, "PMB_ERROR_DATA_NOT_READY"},
    {5891, "CSI2TX_ERROR_UNDERFLOW"},
    {2307, "VTIMING_ERROR_TGMEMHI_NOT_OK"},
    {259, "EXCEPTIONS_ERROR_PMISALIGN"},
    {7427, "STRBMON_ERROR_AVERAGE"},
    {1290, "VTSENS_ERROR_CLUSTER_FLAG135"},
    {1541, "NVM_ERROR_READ_TIMEOUT"},
    {1042, "CRM_ERROR_CPPOS_CLK_TARGET"},
    {6912, "SPI2S3_ERROR_TIMEOUT"},
    {1047, "CRM_ERROR_HOST_CLK_TARGET"},
    {257, "EXCEPTIONS_ERROR_OPCODE"},
    {36, "TOP_ERROR_BAD_DEVICE_IMMUNITY_RANGE"},
    {2560, "DESCRAMBLER_ERROR_VERSION"},
    {21, "TOP_ERROR_LASER_DRIVER_CRC_INVALID"},
    {1306, "VTSENS_ERROR_CLUSTER_FLAG135_OVERFLOW"},
    {27, "TOP_ERROR_CSI2TX_CLK_READY_TIMEOUT"},
    {39, "TOP_WARNING_SLAVE_PULSE_IGNORED"},
    {5888, "CSI2TX_ERROR_VERSION"},
    {3334, "DARKCAL_ERROR_BAD_NUM_BLACK_LINES_HW_CONFIG"},
    {7424, "STRBMON_ERROR_VERSION"},
    {5632, "CLKCHANGER_ERROR_VERSION"},
    {515, "XP70PATCH_ERROR_BAD_CRC"},
    {42, "TOP_ERROR_LASER_GPIO_1_3_CONFIG"},
    {265, "EXCEPTIONS_ERROR_DWRITE"},
    {7680, "FRAMEFORMATER_ERROR_VERSION"},
    {3337, "DARKCAL_ERROR_BAD_LEAKY_PRECISION_W_HW_CONFIG"},
    {1296, "VTSENS_ERROR_OVERFLOW"},
    {4356, "ISLGEN2_ERROR_MEMORY_LOCKED"},
    {4354, "ISLGEN2_ERROR_MISSED_TRIGGER"},
    {6400, "TCU_ERROR_INVALID_CYCLES_COUNT"},
    {266, "EXCEPTIONS_ERROR_PSYSERR"},
    {1282, "VTSENS_ERROR_CLUSTER"},
    {512, "XP70PATCH_ERROR_PATCH_CODE_TOO_LARGE"},
    {1286, "VTSENS_ERROR_CLUSTER_FLAG125"},
    {34, "TOP_ERROR_BAD_FRAME_SEQUENCER_CONFIG"},
    {3332, "DARKCAL_ERROR_BAD_DARK_CHANNELS_W_HW_CONFIG"},
    {1295, "VTSENS_ERROR_MODE_CLUSTER_FLAG125_FLAG135"},
    {1043, "CRM_ERROR_CPNEG_CLK_TARGET"},
    {1031, "CRM_ERROR_PLL_ITOF_EXT_CLK"},
    {1544, "NVM_ERROR_WRITE_FAIL"},
    {25, "TOP_ERROR_NVM_FA_RETURN_INVALID"},
    {256, "EXCEPTIONS_ERROR_PROTECT"},
    {1291, "VTSENS_ERROR_MODE_CLUSTER_FLAG135"},
    {264, "EXCEPTIONS_ERROR_DREAD"},
    {1281, "VTSENS_ERROR_MODE"},
    {1309, "VTSENS_ERROR_MODE_FLAG125_FLAG135_OVERFLOW"},
    {267, "EXCEPTIONS_ERROR_OVERFLOW"},
    {1307, "VTSENS_ERROR_MODE_CLUSTER_FLAG135_OVERFLOW"},
    {1033, "CRM_ERROR_PLL_ITOF_MULT_CONFIG"},
    {1300, "VTSENS_ERROR_FLAG125_OVERFLOW"},
    {0, "TOP_ERROR_NO_ERROR"},
    {1294, "VTSENS_ERROR_CLUSTER_FLAG125_FLAG135"},
    {1044, "CRM_ERROR_DAC_CLK_TARGET"},
    {2308, "VTIMING_ERROR_TGMEMHI_FALLING"},
    {1302, "VTSENS_ERROR_CLUSTER_FLAG125_OVERFLOW"},
    {2311, "VTIMING_ERROR_BGISON_NOT_OK"},
    {1298, "VTSENS_ERROR_CLUSTER_OVERFLOW"},
    {1041, "CRM_ERROR_PLL_ITOF_LOCK_TIMEOUT"},
    {3338, "DARKCAL_ERROR_BAD_ADC_OFFSET_W_HW_CONFIG"},
    {22, "TOP_ERROR_CLOCK_CHECKER"},
    {3330, "DARKCAL_ERROR_BAD_MACROPIX_W_HW_CONFIG"},
    {261, "EXCEPTIONS_ERROR_PEXECUTE"},
    {40, "TOP_WARNING_DPC_COORDINATE_OUT_OF_RANGE"},
    {1292, "VTSENS_ERROR_FLAG125_FLAG135"},
    {1026, "CRM_ERROR_PLL_SYS_FREQ_MIN"},
    {2315, "VTIMING_ERROR_SYNC_MODE_NOT_SUPPORTED"},
    {1547, "NVM_ERROR_LOCK_FAIL"},
    {1287, "VTSENS_ERROR_MODE_CLUSTER_FLAG125"},
    {1539, "NVM_ERROR_ADDRESS_TOO_FAR"},
    {1299, "VTSENS_ERROR_MODE_CLUSTER_OVERFLOW"},
    {1546, "NVM_ERROR_STICK_FAIL"},
    {1536, "NVM_ERROR_READ_CORRECTED_ECC"},
    {2305, "VTIMING_ERROR_BOOT_LOADER_RELOADING"},
    {1297, "VTSENS_ERROR_MODE_OVERFLOW"},
    {18, "TOP_ERROR_INVALID_SPI_ACCESS"},
    {2817, "PATGEN_ERROR_INVALID_PATTERN"},
    {1049, "CRM_ERROR_THSENS_CLK_TARGET"},
    {2306, "VTIMING_ERROR_TOKEN_MISMATCH"},
    {28, "TOP_ERROR_NMI_INTERRUPT"},
    {1028, "CRM_ERROR_PLL_OIF_EXT_CLK"},
    {5890, "CSI2TX_ERROR_PKT_TOO_SHORT"},
    {31, "TOP_ERROR_T1_REPLICATOR_ERROR"},
    {2309, "VTIMING_ERROR_AVDD_NOT_OK"},
    {2316, "VTIMING_ERROR_MAX_INTEGRATION_TIME_EXCEEDED"},
    {4, "TOP_ERROR_OIF_STOP_STATE"},
    {7, "TOP_ERROR_FOV_X_SIZE_NOT_MULTIPLE_OF_2"},
    {8, "TOP_ERROR_FOV_X_SIZE_NOT_MULTIPLE_OF_4"},
    {9, "TOP_ERROR_FOV_X_SIZE_NOT_MULTIPLE_OF_8"},
    {24, "TOP_ERROR_NVM_LASER_SAFETY_CRC_INVALID"},
    {1046, "CRM_ERROR_ISP_CLK_TARGET"},
    {20, "TOP_ERROR_WRONG_CONNECTED_LASER_DRIVER"},
    {3336, "DARKCAL_ERROR_BAD_OUT_CHANNEL_W_HW_CONFIG"},
    {1032, "CRM_ERROR_PLL_ITOF_INPUT_RANGE"},
    {1537, "NVM_ERROR_CLK_FREQ"},
    {1037, "CRM_ERROR_PLL_ITOF_CONFIG_FCOVBY2_RANGE"},
    {1310, "VTSENS_ERROR_CLUSTER_FLAG125_FLAG135_OVERFLOW"},
    {16, "TOP_ERROR_FOV_Y_START_TOO_HIGH"},
    {268, "EXCEPTIONS_ERROR_UNKNOWN"},
    {35, "TOP_ERROR_BAD_VIDEO_MODE"},
    {1304, "VTSENS_ERROR_FLAG135_OVERFLOW"},
    {2310, "VTIMING_ERROR_AVDD_FALLING"},
    {3339, "DARKCAL_ERROR_BAD_DATA_FRAC_W_HW_CONFIG"},
    {4352, "ISLGEN2_ERROR_VERSION"},
    {3335, "DARKCAL_ERROR_BAD_NUM_DARK_LINES_HW_CONFIG"},
    {26, "TOP_ERROR_DPHY_TX_DATA_END_TIMEOUT"},
    {1293, "VTSENS_ERROR_MODE_FLAG125_FLAG135"},
    {5120, "FRAMEMERGER_ERROR_VERSION"},
    {6913, "SPI2S3_ERROR_SPI_CLOCK"},
    {1, "TOP_ERROR_STACK"},
    {513, "XP70PATCH_ERROR_TOO_MANY_PATCHES"},
    {1027, "CRM_ERROR_PLL_SYS_MULT_CONFIG"},
    {3333, "DARKCAL_ERROR_BAD_DARK_CHANNELS_H_HW_CONFIG"},
    {1540, "NVM_ERROR_SIZE_TOO_BIG"},
    {5376, "PIXELFORMATTER_ERROR_VERSION"},
    {1039, "CRM_ERROR_PLL_SYS_LOCK_TIMEOUT"},
    {4353, "ISLGEN2_ERROR_INVALID_CFG"},
    {1040, "CRM_ERROR_PLL_OIF_LOCK_TIMEOUT"},
    {1048, "CRM_ERROR_NVM_CLK_TARGET"},
    {32, "TOP_ERROR_ISLGEN_TOP_TIMEOUT"},
    {2816, "PATGEN_ERROR_VERSION"},
    {1312, "VTSENS_ERROR_MEASURE_NOT_READY"},
    {2322, "VTIMING_ERROR_FINE_EXPOSURE_MAX_EXCEEDED"},
    {1289, "VTSENS_ERROR_MODE_FLAG135"},
    {1305, "VTSENS_ERROR_MODE_FLAG135_OVERFLOW"},
    {3, "TOP_ERROR_INVALID_SUB_FRAME_COUNTER"},
    {1545, "NVM_ERROR_WRITE_LOCK"},
    {258, "EXCEPTIONS_ERROR_GPRSIZE"},
    {3340, "DARKCAL_ERROR_BAD_CONFIG"},
    {41, "TOP_ERROR_LASER_CHANNEL_INVALID"},
    {516, "XP70PATCH_ERROR_BAD_PATCH_ADDR"},
    {7428, "STRBMON_ERROR_DISABLE"},
    {263, "EXCEPTIONS_ERROR_DOUTOFMEM"},
    {14, "TOP_ERROR_FOV_X_START_TOO_HIGH"},
    {7426, "STRBMON_ERROR_TON_MAX"},
    {1283, "VTSENS_ERROR_MODE_CLUSTER"},
    {2, "TOP_ERROR_INVALID_CMD"},
    {1029, "CRM_ERROR_PLL_OIF_FREQ_RANGE"},
    {514, "XP70PATCH_ERROR_TOO_MANY_HOOKS"},
    {2304, "VTIMING_ERROR_BOOT_LOADER"},
    {1303, "VTSENS_ERROR_MODE_CLUSTER_FLAG125_OVERFLOW"},
    {3840, "LINEMERGER_ERROR_VERSION"},
    {7425, "STRBMON_ERROR_TOFF_MIN"},
    {1548, "NVM_ERROR_PROG_ON_NON_VIRGIN_WORD"},
    {38, "TOP_ERROR_SLC_STACK_OVERFLOW"},
    {3072, "HDEFCOR_ERROR_VERSION"},
    {1301, "VTSENS_ERROR_MODE_FLAG125_OVERFLOW"},
    {1034, "CRM_ERROR_PLL_ITOF_DIV_CONFIG"},
    {3584, "CROPPER_ERROR_VERSION"},
    {17, "TOP_ERROR_FOV_Y_SIZE_TOO_HIGH"},
    {260, "EXCEPTIONS_ERROR_POUTOFMEM"},
    {2320, "VTIMING_ERROR_STROBE_END_DELAY_P_EXCEEDED"},
    {2323, "VTIMING_ERROR_EXPOSURE_TIME_TOO_LOW"},
    {1024, "CRM_ERROR_PLL_SYS_EXT_CLK"},
    {1542, "NVM_ERROR_READ_ECC_FAIL"},
    {4864, "FIFO2_ERROR_VERSION"},
    {2313, "VTIMING_ERROR_FRAME_LENGTH_READOUT_TOO_LOW"},
    {29, "TOP_ERROR_EXTSYNC_ALLOCATION"},
    {1036, "CRM_ERROR_PLL_ITOF_CONFIG_NOT_FOUND"},
    {2325, "VTIMING_ERROR_SLAVE_LATENCY"},
    {23, "TOP_ERROR_UNSUPPORTED_LASER_DRIVER"},
    {262, "EXCEPTIONS_ERROR_DMISALIGN"},
    {4355, "ISLGEN2_ERROR_TOO_MANY_ENTRIES"},
    {2319, "VTIMING_ERROR_STROBE_END_DELAY_L_EXCEEDED"},
    {2314, "VTIMING_ERROR_BAD_VIDEO_MODE"},
    {5892, "CSI2TX_ERROR_LANE_DESYNC"},
    {1792, "FLEXSLAVEHCI_ERROR_VERSION"},
    {1538, "NVM_ERROR_NULL_PTR"},
    {1030, "CRM_ERROR_PLL_OIF_MULT_CONFIG"},
    {15, "TOP_ERROR_FOV_X_SIZE_TOO_HIGH"},
    {7937, "PMB_ERROR_DATA_READY_LOW_TIMEOUT"},
    {19, "TOP_ERROR_LASER_DRIVER_READY"},
    {2324, "VTIMING_ERROR_DEFAULT_BOOT_LOADER_TIMINGS"},
    {43, "TOP_ERROR_LASER_DRIVER_OTP_CRC_INVALID"},
    {11, "TOP_ERROR_FOV_Y_START_NOT_MULTIPLE_OF_4"},
    {3329, "DARKCAL_ERROR_VERSION"},
    {10, "TOP_ERROR_FOV_Y_START_NOT_MULTIPLE_OF_2"},
    {3328, "DARKCAL_ERROR_NULL_PTR"},
    {5889, "CSI2TX_ERROR_PKT_TOO_LONG"},
    {30, "TOP_ERROR_SLAVE_BAD_CONFIGURATION"},
    {1025, "CRM_ERROR_PLL_SYS_PIX_CLK"},
    {2327, "VTIMING_ERROR_SUPERFRAME_LENGTH_TOO_LOW"},
    {2312, "VTIMING_ERROR_BGISON_FALLING"},
    {2318, "VTIMING_ERROR_STROBE_START_DELAY_P_EXCEEDED"},
    {2326, "VTIMING_ERROR_LAST_SF_FRAME_LENGTH"},
    {2321, "VTIMING_ERROR_STROBE_LENGTH_TOO_LOW"},
    {12, "TOP_ERROR_FOV_Y_SIZE_NOT_MULTIPLE_OF_2"},
    {1050, "CRM_ERROR_SSCG_CFG_OVERFLOW"},
    {1035, "CRM_ERROR_PLL_ITOF_CONFIG_DIV"},
    {2317, "VTIMING_ERROR_STROBE_START_DELAY_L_EXCEEDED"},
    {1288, "VTSENS_ERROR_FLAG135"},
    {13, "TOP_ERROR_FOV_Y_SIZE_NOT_MULTIPLE_OF_4"},
    {1038, "CRM_ERROR_PLL_ITOF_CONFIG_ODF2D"},
    {2048, "WINDOWING_ERROR_VERSION"},
    {3331, "DARKCAL_ERROR_BAD_MACROPIX_H_HW_CONFIG"},
    {4608, "MP2R_ERROR_VERSION"},
    {37, "TOP_ERROR_NULL_RANDOM_SEED"}
};

const __LUT_CODES lut_nvm_error_codes[] = {
    {14, "LOCK_ERROR"}, {10, "VIRGINITY_ERROR"}, {0, "NO_ERROR"},
    {2, "READ_FAIL"}, {15, "STICK_ERROR"}, {5, "PROG_ON_NON_VIRGIN_WORD"},
    {3, "PROG_FAIL"}, {1, "BAD_CONFIG"}, {4, "ECC_CORRECTION_FAIL"}
};

const __LUT_CODES lut_system_fsm_codes[] = {
    {255, "HALT"}, {0, "HW_STBY"}, {7, "SW_STBY"}, {4, "BOOT"},
    {170, "FW_STALL"}, {8, "STREAMING"}, {1, "SYSTEM_UP"}
};

const __LUT_CODES lut_boot_fsm_codes[] = {
    {1, "MAIN_ENTRY"}, {32, "TEMPERATURE_READ"}, {170, "WAITING_CMD"},
    {0, "HW_STBY"}, {80, "FWP_SETUP"}, {2, "CLOCK_INIT"},
    {188, "BOOT_COMPLETED"}, {18, "SYSTEM_BOOT"}, {17, "NVM_UNPACK"},
    {48, "I2C_ADDR_UPDATE"}, {16, "NVM_DWLD"}

};

const __LUT_REG lut_vd55h1_reg_tbl[] = {
    {0x0000, "DEVICE_MODEL_ID"},
    {0x0004, "DEVICE_REVISION"},
    {0x000A, "ROM_REVISION"},
    {0x000C, "FWPATCH_REVISION"},
    {0x0054, "SYSTEM_FSM"},
    {0x0055, "BOOT_FSM"},
    {0x005C, "NVM"},
    {0x00B0, "ERROR_CODE"},
    {0x00B2, "WARNING_CODE"},
    {0x00D4, "LD_0"},
    {0x00EC, "LD_24"},
    {0x00F2, "LD_30"},
    {0x00FB, "LD_39"},
    {0x0104, "LD_48"},
    {0x0107, "LD_51"},
    {0x0114, "LD_64"},
    {0x012D, "LD_89"},
    {0x0212, "SENSOR_TEMPERATURE"},
    {0x0704, "EWS_TOP_CHIP_ID_1"},
    {0x0708, "EWS_TOP_CHIP_ID_2"},
    {0x0710, "EWS_BOT_CHIP_ID_1"},
    {0x0714, "EWS_BOT_CHIP_ID_2"},
    {0x0900, "LD_0"},
    {0x0918, "LD_24"},
    {0x091E, "LD_30"},
    {0x0927, "LD_39"},
    {0x0930, "LD_48"},
    {0x0933, "LD_51"},
    {0x0940, "LD_64"},
    {0x0959, "LD_89"},
};

std::string get_name_by_err_code (unsigned short error_code)
{
    unsigned int lut_err_code_array_size = sizeof(lut_error_codes) / sizeof(lut_error_codes[0]);

    for (unsigned int ix = 0; ix < lut_err_code_array_size; ix++) {
        if (error_code == lut_error_codes[ix].code) {
            return (lut_error_codes[ix].name);
        }
    }

    return ("");
}

std::string get_name_by_system_fsm_code (unsigned short sys_fsm_code)
{
    unsigned int lut_system_fsm_array_size = sizeof(lut_system_fsm_codes) / sizeof(lut_system_fsm_codes[0]);

    for (unsigned int ix = 0; ix < lut_system_fsm_array_size; ix++) {
        if (sys_fsm_code == lut_system_fsm_codes[ix].code) {
            return (lut_system_fsm_codes[ix].name);
        }
    }

    return ("");
}

std::string get_name_by_boot_fsm_code (unsigned short boot_fsm_code)
{
    unsigned int lut_boot_fsm_array_size = sizeof(lut_boot_fsm_codes) / sizeof(lut_boot_fsm_codes[0]);

    for (unsigned int ix = 0; ix < lut_boot_fsm_array_size; ix++) {
        if (boot_fsm_code == lut_boot_fsm_codes[ix].code) {
            return (lut_boot_fsm_codes[ix].name);
        }
    }

    return ("");
}

std::string get_name_by_reg_addr (unsigned short reg_addr)
{
    unsigned int lut_vd55h1_reg_tbl_size = sizeof(lut_vd55h1_reg_tbl) / sizeof(lut_vd55h1_reg_tbl[0]);

    for (unsigned int ix = 0; ix < lut_vd55h1_reg_tbl_size; ix++) {
        if (reg_addr == lut_vd55h1_reg_tbl[ix].reg_addr) {
            return (lut_vd55h1_reg_tbl[ix].reg_name);
        }
    }

    return ("");
}

